"""Static seed content for Ayojan Wale marketplace."""

IMG = {
    "marigold_henna": "https://images.unsplash.com/photo-1771992228898-79342c9c1c39?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
    "marigold_garland": "https://images.unsplash.com/photo-1607512566084-a20ed291d623?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
    "marigold_close": "https://images.unsplash.com/photo-1699764681875-dd04ce36b1c3?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
    "hanging_decor": "https://images.unsplash.com/photo-1589463349208-95817c91f971?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
    "photographer": "https://images.unsplash.com/photo-1565689477829-14d5871f5bda?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
    "camera": "https://images.unsplash.com/photo-1609085178848-b2de5927eda7?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
    "makeup1": "https://images.unsplash.com/photo-1684868682581-4cac3af5b8d4?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
    "makeup2": "https://images.unsplash.com/photo-1684868265714-fd2300637c23?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
    "balloons": "https://images.unsplash.com/photo-1504196606672-aef5c9cefc92?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
    "birthday": "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
    "venue_dinner": "https://images.unsplash.com/photo-1519167758481-83f550bb49b3?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
    "venue_hall": "https://images.unsplash.com/photo-1712314947761-a8d718bd8c32?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
    "venue_ornate": "https://images.unsplash.com/photo-1655516433028-9e0e1599cf8b?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
    "food_platter": "https://images.unsplash.com/photo-1555244162-803834f70033?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
    "food_indian": "https://images.unsplash.com/photo-1728910156510-77488f19b152?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
    "dj_concert": "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
    "dj_terminal": "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
    "dj_crowd": "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
    "cake1": "https://images.unsplash.com/photo-1670529775317-d744808e7f17?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
    "cake2": "https://images.unsplash.com/photo-1719512037487-78e399b58a53?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
    "stage_mandap": "https://images.unsplash.com/photo-1591203281954-23fa2ff8ef18?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
    "stage_purple": "https://images.unsplash.com/photo-1608713709464-04cfb951c93f?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
    "stage_sofa": "https://images.unsplash.com/photo-1640355105827-2aa98e908a7b?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
    "diya_hands": "https://images.unsplash.com/photo-1605292356183-a77d0a9c9d1d?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
    "diya_rangoli": "https://images.unsplash.com/photo-1577083753695-e010191bacb5?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
}

CATEGORIES = [
    {"slug": "photography", "name": "Photography", "icon": "camera", "image": IMG["photographer"], "vendor_count": 124, "accent": "plum"},
    {"slug": "decoration", "name": "Decoration", "icon": "flower", "image": IMG["stage_mandap"], "vendor_count": 98, "accent": "marigold"},
    {"slug": "catering", "name": "Catering", "icon": "utensils", "image": IMG["food_indian"], "vendor_count": 76, "accent": "saffron"},
    {"slug": "music-dj", "name": "Music & DJ", "icon": "music", "image": IMG["dj_terminal"], "vendor_count": 54, "accent": "coral"},
    {"slug": "makeup", "name": "Makeup", "icon": "sparkles", "image": IMG["makeup1"], "vendor_count": 62, "accent": "coral"},
    {"slug": "entertainment", "name": "Entertainment", "icon": "mic", "image": IMG["dj_crowd"], "vendor_count": 41, "accent": "plum"},
    {"slug": "cakes", "name": "Cakes", "icon": "cake", "image": IMG["cake2"], "vendor_count": 37, "accent": "coral"},
    {"slug": "venues", "name": "Venues", "icon": "building", "image": IMG["venue_hall"], "vendor_count": 88, "accent": "gold"},
    {"slug": "event-setup", "name": "Event Setup", "icon": "tent", "image": IMG["stage_purple"], "vendor_count": 45, "accent": "marigold"},
    {"slug": "gifts", "name": "Gifts & Favours", "icon": "gift", "image": IMG["marigold_garland"], "vendor_count": 29, "accent": "gold"},
    {"slug": "transport", "name": "Transport", "icon": "car", "image": IMG["venue_ornate"], "vendor_count": 22, "accent": "plum"},
]

EVENT_TYPES = [
    {"slug": "wedding", "name": "Wedding", "icon": "gem", "image": IMG["marigold_henna"], "theme": "wedding", "tagline": "Plum, gold & marigold"},
    {"slug": "birthday", "name": "Birthday", "icon": "cake", "image": IMG["balloons"], "theme": "birthday", "tagline": "Coral, peach & joy"},
    {"slug": "baby-shower", "name": "Baby Shower", "icon": "baby", "image": IMG["cake1"], "theme": "baby", "tagline": "Soft peach & mint"},
    {"slug": "housewarming", "name": "Housewarming", "icon": "home", "image": IMG["venue_dinner"], "theme": "wedding", "tagline": "Warm & welcoming"},
    {"slug": "religious", "name": "Religious Ceremony", "icon": "flame", "image": IMG["diya_rangoli"], "theme": "religious", "tagline": "Saffron & marigold"},
    {"slug": "graduation", "name": "Graduation", "icon": "graduation-cap", "image": IMG["dj_crowd"], "theme": "corporate", "tagline": "Proud moments"},
    {"slug": "corporate", "name": "Corporate Event", "icon": "briefcase", "image": IMG["venue_hall"], "theme": "corporate", "tagline": "Plum & subtle grey"},
    {"slug": "anniversary", "name": "Anniversary", "icon": "heart", "image": IMG["stage_sofa"], "theme": "wedding", "tagline": "Timeless & elegant"},
]


def _v(id, name, cat_slug, cat_name, city, price, rating, reviews, image, event_types, tagline, packages, gallery):
    return {
        "id": id, "name": name, "category_slug": cat_slug, "category_name": cat_name,
        "city": city, "starting_price": price, "rating": rating, "reviews": reviews,
        "image": image, "event_types": event_types, "tagline": tagline,
        "packages": packages, "gallery": gallery,
    }


def _pk(name, price, features):
    return {"name": name, "price": price, "features": features}


VENDORS = [
    _v("v1", "Royal Moments Photography", "photography", "Photography", "Jodhpur", 15000, 4.8, 214,
       IMG["photographer"], ["wedding", "anniversary", "corporate"], "Candid & cinematic wedding stories",
       [_pk("Half Day", 15000, ["4 hours coverage", "1 photographer", "150 edited photos"]),
        _pk("Full Wedding", 45000, ["2 photographers", "Cinematic film", "500+ edited photos", "Photo album"])],
       [IMG["photographer"], IMG["camera"], IMG["marigold_henna"]]),
    _v("v2", "Gulmohar Decor Studio", "decoration", "Decoration", "Jaipur", 25000, 4.9, 176,
       IMG["stage_mandap"], ["wedding", "religious", "anniversary"], "Floral mandaps & stage artistry",
       [_pk("Stage Decor", 25000, ["Backdrop setup", "Fresh flowers", "Ambient lighting"]),
        _pk("Full Venue", 90000, ["Entrance decor", "Mandap", "Table centrepieces", "Lighting"])],
       [IMG["stage_mandap"], IMG["stage_purple"], IMG["hanging_decor"]]),
    _v("v3", "Rajwada Caterers", "catering", "Catering", "Udaipur", 550, 4.7, 302,
       IMG["food_indian"], ["wedding", "corporate", "housewarming"], "Authentic Rajasthani thali & live counters",
       [_pk("Per Plate Silver", 550, ["Veg thali", "3 starters", "2 desserts"]),
        _pk("Per Plate Gold", 950, ["Veg + non-veg", "Live counters", "5 desserts", "Welcome drinks"])],
       [IMG["food_indian"], IMG["food_platter"], IMG["venue_dinner"]]),
    _v("v4", "BeatBox DJ & Sound", "music-dj", "Music & DJ", "Jaipur", 18000, 4.6, 141,
       IMG["dj_terminal"], ["wedding", "birthday", "graduation"], "High-energy sets & pro sound systems",
       [_pk("Party Pack", 18000, ["4 hours DJ", "Sound system", "Basic lights"]),
        _pk("Grand Night", 40000, ["6 hours DJ", "LED wall", "Smoke + laser", "MC host"])],
       [IMG["dj_terminal"], IMG["dj_concert"], IMG["dj_crowd"]]),
    _v("v5", "Aashna Bridal Makeup", "makeup", "Makeup", "Jodhpur", 12000, 4.9, 268,
       IMG["makeup1"], ["wedding", "anniversary", "birthday"], "HD & airbrush bridal looks",
       [_pk("Party Makeup", 12000, ["1 look", "Hair styling", "Draping"]),
        _pk("Bridal Package", 35000, ["Bridal look", "2 family members", "Trial session", "Touch-up kit"])],
       [IMG["makeup1"], IMG["makeup2"], IMG["marigold_henna"]]),
    _v("v6", "Encore Entertainment", "entertainment", "Entertainment", "Mumbai", 30000, 4.5, 89,
       IMG["dj_crowd"], ["wedding", "corporate", "anniversary"], "Live bands, anchors & performers",
       [_pk("Solo Artist", 30000, ["1 performer", "2 hour set", "Own equipment"]),
        _pk("Live Band", 85000, ["5-piece band", "Sound + lights", "Custom playlist"])],
       [IMG["dj_crowd"], IMG["dj_concert"], IMG["stage_purple"]]),
    _v("v7", "Sugarcraft Bakehouse", "cakes", "Cakes", "Jaipur", 2500, 4.8, 197,
       IMG["cake2"], ["birthday", "baby-shower", "anniversary"], "Custom celebration & tiered cakes",
       [_pk("Single Tier", 2500, ["2kg", "Custom flavour", "Basic design"]),
        _pk("Wedding Tier", 12000, ["3 tiers", "Fondant art", "Fresh flowers", "Delivery"])],
       [IMG["cake2"], IMG["cake1"], IMG["balloons"]]),
    _v("v8", "Heritage Palace Banquets", "venues", "Venues", "Udaipur", 120000, 4.9, 156,
       IMG["venue_hall"], ["wedding", "corporate", "anniversary"], "Regal halls & lawns by the lake",
       [_pk("Hall (200 pax)", 120000, ["AC banquet", "Basic decor", "Parking"]),
        _pk("Palace Lawn", 350000, ["Open lawn", "Poolside", "Suites", "In-house catering"])],
       [IMG["venue_hall"], IMG["venue_ornate"], IMG["venue_dinner"]]),
    _v("v9", "Utsav Event Setup", "event-setup", "Event Setup", "Delhi", 40000, 4.6, 73,
       IMG["stage_purple"], ["wedding", "corporate", "religious"], "Tents, stages & complete setups",
       [_pk("Basic Setup", 40000, ["Stage + seating", "Canopy", "Basic lighting"]),
        _pk("Grand Setup", 150000, ["Themed setup", "Multiple zones", "Premium furniture"])],
       [IMG["stage_purple"], IMG["stage_sofa"], IMG["stage_mandap"]]),
    _v("v10", "Shubh Gifting Co.", "gifts", "Gifts & Favours", "Jaipur", 150, 4.7, 64,
       IMG["marigold_garland"], ["wedding", "religious", "housewarming"], "Curated return gifts & hampers",
       [_pk("Return Gift", 150, ["Per piece", "Gift wrap", "Custom tag"]),
        _pk("Luxury Hamper", 1500, ["Assorted goodies", "Premium box", "Personalised note"])],
       [IMG["marigold_garland"], IMG["marigold_close"], IMG["hanging_decor"]]),
    _v("v11", "Marudhar Luxury Cars", "transport", "Transport", "Jodhpur", 8000, 4.5, 51,
       IMG["venue_ornate"], ["wedding", "anniversary", "corporate"], "Vintage & luxury car rentals",
       [_pk("Sedan (per day)", 8000, ["AC sedan", "Chauffeur", "100 km"]),
        _pk("Vintage Car", 25000, ["Decorated classic", "Chauffeur", "Photoshoot ready"])],
       [IMG["venue_ornate"], IMG["venue_hall"], IMG["stage_sofa"]]),
    _v("v12", "Divya Diyas & Rituals", "decoration", "Decoration", "Udaipur", 9000, 4.8, 88,
       IMG["diya_rangoli"], ["religious", "housewarming", "wedding"], "Traditional puja & festive decor",
       [_pk("Puja Setup", 9000, ["Rangoli", "Diyas", "Floral"]),
        _pk("Festive Decor", 30000, ["Full home decor", "Torans", "Lighting", "Pandit coordination"])],
       [IMG["diya_rangoli"], IMG["diya_hands"], IMG["marigold_close"]]),
    _v("v13", "Frame & Focus Studio", "photography", "Photography", "Mumbai", 20000, 4.7, 130,
       IMG["camera"], ["birthday", "corporate", "graduation"], "Event & pre-wedding specialists",
       [_pk("Event Coverage", 20000, ["4 hours", "1 photographer", "200 photos"]),
        _pk("Pre-Wedding", 35000, ["Half-day shoot", "2 locations", "Cinematic reel"])],
       [IMG["camera"], IMG["photographer"], IMG["balloons"]]),
    _v("v14", "Confetti Kids Parties", "event-setup", "Event Setup", "Delhi", 15000, 4.9, 112,
       IMG["balloons"], ["birthday", "baby-shower"], "Themed kids' party specialists",
       [_pk("Theme Party", 15000, ["Balloon decor", "Backdrop", "Games host"]),
        _pk("Grand Bash", 40000, ["Custom theme", "Entertainers", "Cake + favours", "Photo booth"])],
       [IMG["balloons"], IMG["birthday"], IMG["cake1"]]),
]

IDEAS = [
    {"slug": "wedding-decor-trends", "title": "Trending Wedding Decoration Ideas", "category": "Wedding",
     "image": IMG["stage_mandap"], "excerpt": "From floral mandaps to fairy-lit walkways — the looks defining this season.", "read": "6 min read"},
    {"slug": "birthday-themes", "title": "10 Birthday Themes Everyone Will Love", "category": "Birthday",
     "image": IMG["balloons"], "excerpt": "Playful, bold and memorable themes for every age group.", "read": "5 min read"},
    {"slug": "traditional-celebration", "title": "Beautiful Ideas for a Traditional Indian Celebration", "category": "Festive",
     "image": IMG["diya_rangoli"], "excerpt": "Honour the rituals while keeping the aesthetic elegant and modern.", "read": "7 min read"},
    {"slug": "choose-decorator", "title": "How to Choose the Right Decorator", "category": "Guide",
     "image": IMG["hanging_decor"], "excerpt": "The questions to ask before you lock in your decor partner.", "read": "4 min read"},
]
